# Generated by Django 4.1.2 on 2022-11-02 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_location', models.CharField(max_length=100)),
                ('state_location', models.CharField(max_length=100)),
                ('more_specific_location', models.CharField(max_length=100)),
                ('max_rent', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('user_gender', models.CharField(max_length=20)),
                ('roomate_gender', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
