# Generated by Django 4.1.2 on 2022-11-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_attributes',
            table='user_attributes',
        ),
    ]
